version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432" # host:container (use 5433 since 5432 is already taken on your machine)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: